trigger: none

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - bash: echo "##vso[task.setvariable variable=pkg.version;isOutput=true]9.9.9"
      name: A11
      displayName: Create vars
  - template: templates/job_A.yaml

- stage: B
  dependsOn: A
  variables:
    # Syntax is important here. Only runtime expressions work (stageDependencies doesn't exist yet)
    pkg.version.stage.set_in_main: $[ stageDependencies.A.A1.outputs['A11.pkg.version'] ]
    pkg.version.stage.set_in_template: $[ stageDependencies.A.TJA1.outputs['TJA11.pkg.version']]
  jobs:
  - job: B1
    variables:
      pkg.version.job: $[ stageDependencies.A.A1.outputs['A11.pkg.version'] ]
    steps:
    - bash: |
        echo "pkg.version (stage; set in main): "$(pkg.version.stage.set_in_main)
        echo "pkg.version (stage; set in template): "$(pkg.version.stage.set_in_template)
        echo "pkg.version (job): "$(pkg.version.job)
      displayName: Check vars
  - template: templates/job_B.yaml
    parameters:
      # Syntax is important here. If ${{ ... }} is used, the runtime expression on the stage vars
      # is not expanded.
      param1: $(pkg.version.stage.set_in_main)
      param2: $(pkg.version.stage.set_in_template)
