trigger:
  branches:
    include:
    - '*'

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - bash: echo "##vso[task.setvariable variable=pkg.version;isOutput=true]9.9.9"
      name: A11
      displayName: Create vars

- stage: B
  dependsOn: A
  variables:
    pkg.version.stage: $[ stageDependencies.A.A1.outputs['A11.pkg.version'] ]
  jobs:
  - job: B1
    variables:
      pkg.version.job: $[ stageDependencies.A.A1.outputs['A11.pkg.version'] ]
    steps:
    - bash: |
        echo "pkg.version (stage): "$(pkg.version.stage)
        echo "pkg.version (job): "$(pkg.version.job)
      displayName: Check vars
  - template: templates/job_B.yaml
    parameters:
      pkg.version: ${{ variables['pkg.version.job'] }}
