trigger:
  branches:
    include:
    - '*'

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - bash: echo "##vso[task.setvariable variable=pkg.version;isOutput=true]9.9.9"
      name: A11

- stage: B
  dependsOn: A
  variables:
    pkg.version: $[ dependencies.A.outputs['A1.A11.pkg.version'] ]
  jobs:
  - job: B1
    steps: 
    - bash: echo $(pkg.version)
